### ISSUE TITLE
Unable to run ng-serve using Angular CLI 1.4.1

### ISSUE THREAD

**Issue by guillermoarellano** [ribizli/ngx-image2dataurl#1]
I am using Angular-CLI v1.4.1.

Have followed the install instructions. The "./module/image-to-data-url" for the import statement is not recognized by Visual Studio Code. I used 'ngx-image2dataurl' for imports statement instead. 

However, now when I do an ng serve from the command line (Win 10 machine), I get an _Error: ImageToDataUrlModule is not an NgModule_ message.

**Comment by ribizli** [comment]
I don't think so that it is related to any CLI version. I created a working StackBlitz example: https://stackblitz.com/edit/angular-fbarcl
I'll update the `readme`, since it uses the developent imports...

**Comment by guillermoarellano** [comment]
This is the error that I am getting. I will try scouring the web another day. Hopefully I can find a solution for others who may be running into the same error. 

[Image - ng serve error](https://www.dropbox.com/s/y7w2cz2csozs78x/ImageToDataUrlModule_error.PNG?dl=0)

**Comment by sudhanshu16** [comment]
Anybody found the solution to this? I am getting the same error 😢
