### ISSUE TITLE
Update peer dependencies

### ISSUE THREAD

**Issue by jpike88** [ribizli/ngx-image2dataurl#11]
>ngx-image2dataurl-orientation@7.0.0 requires a peer of @angular/core@^7.0.0 but none is installed

Needs to be updated to handle angular 8

**Comment by ribizli** [comment]
It's true, that my package was not yet upgraded to v8, but the mentioned package is a fork, not maintained by me. I'll do an upgrade however soon.

**Comment by ribizli** [comment]
Update with support for NG8 is out.
