### ISSUE TITLE
Ionic v4 imageSelected not firing

### ISSUE THREAD

**Issue by casper5822** [ribizli/ngx-image2dataurl#14]
Hello,
i'm using image2dataurl with ionic v4. On the browser it works well.
In a real device the imageSelected event doesn't fire.

Is there any suggestion about how to solve this problem in Ionic?

Antonio.

**Comment by ribizli** [comment]
Sorry, I have zero experience with Ionic.
Can you maybe somehow remote debug the WebView?
Is the DOM event `change` fired from the `<input type="file">`?

You need to find this out yourself, I don't have the setup for this. If you have figured out the bug, I can fix it in the lib, when it is not a limitation of the file input on mobile.

**Comment by ribizli** [comment]
Can this be related? https://stackoverflow.com/questions/46110325/ionicchange-event-is-not-fired-on-ion-input-when-the-input-value-is-changed-f

**Comment by casper5822** [comment]
I just tried with (change) and it works, the event is firing on ionic (mobile smartphone)
