### ISSUE TITLE
import on module

### ISSUE THREAD

**Issue by raimens** [ribizli/ngx-image2dataurl#2]
ERROR in Error: Unexpected value 'ImageToDataUrlModule in /Users/xxxxxxxxx/Documents/repo/serve/web/node_modules/ngx-image2dataurl/src/app/module/image-to-data-url/image-to-data-url.module.d.ts' imported by the module 'AppModule in /Users/rubenmendes/Documents/repo/serve/web/src/app/app.module.ts'. Please add a @NgModule annotation.

**Comment by pablocid** [comment]
I have a similar issue

```
ERROR in Error: ImageToDataUrlModule is not an NgModule
```

**Comment by pptnz** [comment]
@pablocid I have a same issue.

**Comment by ribizli** [comment]
Guys, have you checked the demo? https://stackblitz.com/edit/angular-fbarcl
What is there different?

**Comment by saiyaff** [comment]
I am facing the same issue @pablocid is facing as well.
@ribizli any wisdom? I checked the stackblitz. Nothing wrong has been done in the project.

**Comment by ribizli** [comment]
I'm really busy lately, but I'll check it during the holidays (hopefully).
Are you using angular-cli? Any specific configuration I need to know about?

**Comment by saiyaff** [comment]
Yes, Using angular-cli. Just followed the documentation of this and did the implementations.

This is how the module architecture goes since they're lazily loaded.
app.module(root)
|__public.module
|__secure.module
    |__dashboard.module
    |__models.module
    |__teams.module

The module is imported into every lazily-loaded modules.

**Comment by ribizli** [comment]
Sorry, I cannot reproduce the error with a default `angular-cli` setup.
What I did:
- `ng new ngx-image2dataurl-test --minimal -st`
- `cd ngx-image2dataurl-test`
- `npm install ngx-image2dataurl --save`
- imported module
```typescript
  import { ImageToDataUrlModule } from 'ngx-image2dataurl';
  @NgModule({
    declarations: [
      AppComponent
    ],
    imports: [
      BrowserModule,
      ImageToDataUrlModule,
    ],
    bootstrap: [AppComponent]
  })
  export class AppModule { }
```
- added sample code to component as in README

Maybe you are using wrong import of the module? There is an error in the example on NPM's README, I forgot to replace the path.

**Comment by kconfesor** [comment]
@saiyaff replace the content of the metadata file (node_modules/ngx-image2dataurl/ngx-image2dataurl.metadata.json) with this:

[{"__symbolic":"module","version":3,"metadata":{},"exports":[{"from":"./src/app/module/image-to-data-url"}]},{"__symbolic":"module","version":1,"metadata":{},"exports":[{"from":"./src/app/module/image-to-data-url"}]}]

**Comment by saiyaff** [comment]
@kconfesor thanks for putting it over here. Will try and get back 😄

**Comment by ribizli** [comment]
Can someone point it out, what's different in your setup? Is it happening during AOT, or with cli serve too? I cannot investigate further without reproduction of the issue.

**Comment by sleicht** [comment]
It only happens with `--aot`. It can also be reproduced with the default `angular-cli` setup.

**Comment by sleicht** [comment]
Thanks for the fix!

**Comment by saiyaff** [comment]
Just saw the PR. Thanks for the fix. @ribizli
