### ISSUE TITLE
Reopening the same image

### ISSUE THREAD

**Issue by ctenden** [ribizli/ngx-image2dataurl#3]
The imageSelected binding is not firing when trying to upload the same image twice in a row.

While it seems dumb to do so, I have an edit screen after the image upload, and if they cancel, and retry, it fails until they upload a new image, cancel and reupload the first image again.

**Comment by ribizli** [comment]
This is a known issue with HTML inpit, it doesn't fire on selecting the same image. Try to programmatically remove the selection of the input from the handler, so the reselection fires again.

**Comment by ribizli** [comment]
I'm not sure if it can be done however, sorry.

**Comment by ribizli** [comment]
After some reading, the best way is to wrap it into a form and reset the form..

**Comment by ctenden** [comment]
Okay thanks, will try it.

**Comment by ctenden** [comment]
That suggestion worked well.  thanks

**Comment by jpike88** [comment]
@ribizli there's a better technique here that allows you to wrap around a button element, and also prevents this bug from occurring:

https://github.com/boxxxie/angularjs-imageupload-directive/blob/master/src/imageupload.js

**Comment by ribizli** [comment]
@jpike88 as far as I see this also does a `form.reset()` call on a wrapper form. The cool part of the linked solution is however that the file `input` is not included into the document at all. Thanks for the info.
