### ISSUE TITLE
Angular 11 compatibility?

### ISSUE THREAD

**Issue by casper5822** [ribizli/ngx-image2dataurl#31]
Hello,
Does the latest version work with angular 11?

**Comment by ribizli** [comment]
this lib is not actively maintained anymore,  the letest officially supported ng version was 10. however a very few ng API is used, so most probably it will still work. it is still compiled with viewengine but it shouldn't be a problem

**Comment by ribizli** [comment]
I created a new release (12.1.0) where >=ng10 is the peer dependency, so all ng10, ng11 and ng12 are supported.

@casper5822 can you please test it with your ng11 version?

**Comment by casper5822** [comment]
Thank you i Will test it and give you a feedback

**Comment by casper5822** [comment]
@ribizli i tested it and it works and for me it works. Thanks
