### ISSUE TITLE
Handle Heic file format

### ISSUE THREAD

**Issue by oliveti** [ribizli/ngx-image2dataurl#37]
Hi,

First, thank you for this awesome library. 

I'm using the resizing feature and the resize property is not valued when user select sa HEIC photo. 

Would there be a way to handle this file format ?

Thank you

**Comment by ribizli** [comment]
I don't plan to include any lib to support HEIC directly.

I'd try to create a `IMAGE_FILE_PROCESSOR` with https://github.com/alexcorvi/heic2any.
