### ISSUE TITLE
Low quality resized image

### ISSUE THREAD

**Issue by dmjones500** [ribizli/ngx-image2dataurl#4]
I'm resizing the selected image with the following settings:

```
  options: Options = {
    resize: {
      maxHeight: 500,
      maxWidth: 500,
      quality: 0.9,
    },
    allowedExtensions: ['JPG', 'PnG']
  };
```

I show the resulting image on my form, after selection, using a simple `<img *ngIf="src" src="{{src}}">`. The resized image always looks low quality and jagged.

Is there any way to improve this? What algorithm are you using for resizing?

**Comment by ribizli** [comment]
I draw the original image into a canvas with the desired dimensions. https://github.com/ribizli/ngx-image2dataurl/blob/master/src/app/module/image-to-data-url/utils.ts
If the original image is near to that size, that's a known scaling issue in graphics.

**Comment by dmjones500** [comment]
OK, thanks. It results in fairly poor results in Safari on Mac.

Have you considered supporting higher quality resize algorithms? A bit of research suggests the standard canvas scaling often results in poor quality.

E.g. as per https://gist.github.com/transitive-bullshit/37bac5e741eaec60e983 or https://github.com/danschumann/limby-resize.

**Comment by ribizli** [comment]
I might consider a plugable resize feature, and one can replace it for his/her need. But as default I'd keep it as simple as it is now.

**Comment by dmjones500** [comment]
OK, thank you. In the meantime I'll look for another library.
