### ISSUE TITLE
Building with --aot errors: "Directive ɵa, Property 'readFiles' is private and only accessible within class 'ImageToDataUrlDirective'"

### ISSUE THREAD

**Issue by bporter-a3digital** [ribizli/ngx-image2dataurl#5]
Just got this npm package today and thought it was PERFECT for our application. It worked and built fine. However, when our build server used --aot to build it (using Angular 5.2.9), we're getting the following error:

**"ERROR in ...image.component.html(7,5): : Directive ɵa, Property 'readFiles' is private and only accessible within class 'ImageToDataUrlDirective'"**

I followed the posted example very closely. From my research, it doesn't seem like there's a way for me to get around this error without a change to the package. :/

Would it be acceptable to change the relevant private methods within the ImageToDataUrlDirective to be public, so that building with --aot also works?

**Comment by ribizli** [comment]
This is strange, that nobody has reported this before. I just didn't know about that `@HostListener` methods need to be public for AOT (I thought only attributes and methods used in template need to be). Anyway I'll provide a fix soon.

**Comment by ribizli** [comment]
Ok, so I've made a short test, and seems that in my minimal example (same as in the README) works the AOT compilation without error. Can you please give me more info, how to reproduce?

**Comment by bporter-a3digital** [comment]
Hmmm... okay, let me give you some more detail:

In our Angular project, there's a "check deposit" module, and I've added "ImageToDataUrlModule" to the imports there.

Within our module, I have a CheckImageComponent. Its template is normal html and includes the code:

`<input type="file" [imageToDataUrl]="options" (imageSelected)="checkImageUploaded($event)">`

And here's the component itself:

`import { Component, ElementRef, EventEmitter, Input, Output, ViewChild } from '@angular/core';
import { Subscription } from 'rxjs/Rx';
import { Options, ImageResult } from 'ngx-image2dataurl';

@Component({
  selector: 'app-check-image',
  templateUrl: './check-image.component.html'
})
export class CheckImageComponent {
  @ViewChild('checkUploadLabel') checkUploadLabel: ElementRef;
  @Input() checkImagePath: string;
  @Input() checkSide: string;
  @Output() setImagePath = new EventEmitter<object>();

  public options: Options = {
    resize: {
      maxHeight: 800,
      maxWidth: 800
    },
    allowedExtensions: ['jpg', 'jpeg', 'png']
  };

  public uploadNewImage(): void {
    this.checkUploadLabel.nativeElement.click();
  }

  public checkImageUploaded(imageResult: ImageResult): void {
    if (imageResult.error) {
      // tslint:disable-next-line:no-console
      console.error(imageResult.error);
    }
    const src = imageResult.resized && imageResult.resized.dataURL || imageResult.dataURL;
    this.setImageSrc(src);
  }

  private setImageSrc(src): void {
    this.checkImagePath = src;
    this.setImagePath.emit({
      side: this.checkSide,
      path: src
    });
  }
}
`

This works fine and dandy, but "ng build --aot" still is giving me _"ERROR in src/app/deposit/check-image.component.html(7,5): : Directive ɵa, Property 'readFiles' is private and only accessible within class 'ImageToDataUrlDirective'."_

**Comment by bporter-a3digital** [comment]
Do you see anything that I'm doing wrong within the code above?

I just changed "private" to "public" on my local ImageToDataUrlDirective, and I no longer get any errors on --aot, so at least it just seems isolated to that.

Thank you so much for helping me out with this, I really appreciate it!!

**Comment by bporter-a3digital** [comment]
@ribizli, if I make a contribution to your repository just changing that private to public on the readFiles method, would you please accept it? It'd be no problem for me to do so. I don't want to make you have to this if you're busy! I just really would like to have this issue resolved by tomorrow for work.

**Comment by ribizli** [comment]
I just couldn't reproduce the error until now, that's why I didn't do the fix.

**Comment by ribizli** [comment]
Which cli version are you using? Seems the latest (1.7.4) doesn't do type checking for me.

**Comment by ribizli** [comment]
Which version of `cli` are you using?

**Comment by bporter-a3digital** [comment]
That's odd -- I'm also on Angular CLI 1.7.4.

**Comment by ribizli** [comment]
Actually in the following example:
```
<img [src]="src" *ngIf="src"><br>
  <input type="file" [imageToDataUrl]="options"
    (imageSelected)="selected($event)">
```
if I set `src` or `selected` private, I get an error about it. But nothing from the module about the private listener. Also strange, that a change to `[src]="src2"` passes the type checking, too (!?).

**Comment by ribizli** [comment]
But anyway, sure it should be public, I'll do the change.

**Comment by bporter-a3digital** [comment]
Huh... that is really strange.

Great though, thank you again for your help on this! 😀
