### ISSUE TITLE
images with transparent background - produces result with black background

### ISSUE THREAD

**Issue by abannsunny** [ribizli/ngx-image2dataurl#6]
I have images I upload with transparent background and after resizing the images have a black background. 

Is there anyway to give a fill so that the resulting images wont have black background? 

solved this:

https://stackoverflow.com/questions/8977369/drawing-png-to-a-canvas-element-not-showing-transparency?rq=1

NB, if you was to use canvas.toDataURL and you set the mimetype to anything other than say gif or png, the transparent parts of the image will be completely black.

 options: Options = {
        resize: {
            maxHeight: 150,
            maxWidth: 200,
            type: 'image/png'
        },
        allowedExtensions: ['jpg', 'jpeg', 'png']
    };

setting type to png solves it!

**Comment by ribizli** [comment]
I draw the image into a resized canvas to read the dataURL out, so more or
less this is browser behaviour. If you could research on this, I'll
integrate the solution (if any). I'd appreciate it.
