### ISSUE TITLE
Peer error with angular 7

### ISSUE THREAD

**Issue by jpike88** [ribizli/ngx-image2dataurl#9]
```ngx-image2dataurl@2.1.1 requires a peer of @angular/core@^6.0.0 but none is installed```

It works fine with angular 7 though.

**Comment by jpike88** [comment]
@ribizli if you're inactive, can you pass npm publish permissions to me? This message is really annoying

**Comment by ribizli** [comment]
I'll upgrade the lib to support Angular 7.0 in the next days.

**Comment by ribizli** [comment]
New version `ngx-image2dataurl@7.0.0` is out now

**Comment by jpike88** [comment]
Cheers mate
